version: '3'

services:
  client:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    command: npm run --prefix frontend serve
    volumes:
      - .:/client
    ports:
      - "8081:8081"
    depends_on: 
      - server
  server:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: python ./backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/server
    ports:
      - "8000:8000"
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data